$src = [System.IO.File]::ReadAllText('verify.ts')
$old = '// 2. Check all CDN scripts exist`nconst scriptRe = /src="(https:\/\/cdn\.jsdelivr\.net[^\"]+)"/g;`nconst urls = [];`nlet m;`nwhile ((m = scriptRe.exec(html))) urls.push(m[1]);`n`nlet cdnOk = 0;`nfor (const url of urls) {`n  await new Promise((resolve) => {`n    https.get(url, (res) => {`n      const name = url.split('/').slice(-2).join('/');`n      if (res.statusCode === 200) { cdnOk++; console.log('[2] CDN ' + name + ': OK'); }`n      else { console.log('[2] CDN ' + name + ': FAIL ' + res.statusCode); }`n      resolve();`n    }).on('error', (e) => {`n      console.log('[2] CDN ERROR:', url.split('/').pop(), e.message);`n      resolve();`n    });`n  });`n}`nconsole.log('[2] CDN scripts: ' + cdnOk + '/' + urls.length + ' OK');`n`n'
$new = '// 2. Check CDN scripts are listed in HTML (fast local check - no network fetch)`nconst scriptRe = /src="(https:\/\/cdn\.jsdelivr\.net[^\"]+)"/g;`nconst urls = [];`nlet m;`nwhile ((m = scriptRe.exec(html))) urls.push(m[1]);`nconsole.log('[2] CDN URLs in HTML: ' + urls.length + ' listed (no network fetch)');`n`n'
$src = $src.Replace($old, $new, [System.Text.ComparisonType]::Ordinal)
$old2 = '// 7. Check key IDs referenced in JS exist in HTML`nconst ids = ['welcomeScreen', 'terminalArea', 'splitRoot', 'agentList', 'agentCount',`n  'targetDir', 'gitBranch', 'connText', 'connStatus', 'activePill',`n  'handoffBtn', 'restartBtn', 'stopBtn', 'splitCount', 'toastContainer',`n  'rateLimitBanner', 'shutdownOverlay', 'sidebar'];`nconst missingIds = ids.filter(id => !html.includes('id=`"'+ id + '`"'));`nif (missingIds.length) {`n  console.log('[7] Missing HTML IDs:', missingIds.join(', '));`n} else {`n  console.log('[7] All ' + ids.length + ' HTML IDs: OK');`n}'
$new2 = '// 7. Dynamic scan: every element id referenced from JS must exist in the HTML`nconst markup = html.replace(/<style>[`s`S]*?</`s'style>/g, "").replace(/<`s'script>[`s`S]*?</`s'script>/g, "");`nconst htmlIds = new Set<string>([...markup.matchAll(/id="([^"]+)"/g)].map(r => r[1]));`nconst referenced = new Set<string>();`nfor (const r of jsMatch[1].matchAll(/getElementById[`\s*["''`]([^"''`']+)[["''`]([`s*`]) `nconst missingIds = [...referenced].filter(id => !htmlIds.has(id) && !id.includes("$"));`nif (missingIds.length) {`n  console.log('[7] Missing HTML IDs:', missingIds.join(', '));`n} else {`n  console.log('[7] All ' + referenced.size + ' JS-referenced IDs exist in the HTML: OK');`n}'
$src = $src.Replace($old2, $new2, [System.Text.ComparisonType]::Ordinal)
[System.IO.File]::WriteAllText('verify.ts', $src, [System.Text.Encoding]::UTF8)
Write-Host 'verify.ts updated'
